import { NextResponse } from 'next/server';
import { getSupabase } from '../../../../../lib/supabase';

// GET /api/admin/items - Get all items
export async function GET(request) {
  try {
    const supabase = getSupabase();
    
    const { data: items, error } = await supabase
      .from('lost_items')
      .select('*')
      .order('created_at', { ascending: false });
    
    if (error) {
      console.error('Database error fetching items:', error);
      return NextResponse.json(
        { success: false, error: `Database error: ${error.message}` },
        { status: 500 }
      );
    }
    
    return NextResponse.json({
      success: true,
      items: items || []
    });
    
  } catch (error) {
    console.error('API Error in GET /api/admin/items:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch items' },
      { status: 500 }
    );
  }
}

// POST /api/admin/items - Create a new item
export async function POST(request) {
  try {
    const body = await request.json();
    const {
      item_name,
      category,
      description,
      location_found,
      location_lost,
      date_found,
      date_lost,
      item_type, // 'lost' or 'found'
      reported_by
    } = body;
    
    // Validation
    if (!item_name || !category || !description || !item_type) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }
    
    if (!['lost', 'found'].includes(item_type)) {
      return NextResponse.json(
        { success: false, error: 'Invalid item type. Must be "lost" or "found"' },
        { status: 400 }
      );
    }
    
    const supabase = getSupabase();
    
    // Create item (unique_item_id will be auto-generated by trigger)
    const itemData = {
      item_name,
      category,
      description,
      item_type,
      status: 'unclaimed',
      reported_by: reported_by || null
    };
    
    // Add type-specific fields
    if (item_type === 'found') {
      itemData.location_found = location_found;
      itemData.date_found = date_found || new Date().toISOString().split('T')[0];
    } else {
      itemData.location_lost = location_lost || location_found;
      itemData.date_lost = date_lost || date_found || new Date().toISOString().split('T')[0];
    }
    
    const { data: newItem, error } = await supabase
      .from('lost_items')
      .insert([itemData])
      .select()
      .single();
    
    if (error) {
      console.error('Database error:', error);
      return NextResponse.json(
        { success: false, error: `Database error: ${error.message}` },
        { status: 500 }
      );
    }
    
    return NextResponse.json({
      success: true,
      message: 'Item created successfully',
      item: newItem
    }, { status: 201 });
    
  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to create item' },
      { status: 500 }
    );
  }
}
