import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {comfortaa,jetbrainsMono, poppins, roboto, playfair} from './utils/fonts'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${comfortaa.variable} ${playfair.variable} ${roboto.variable} ${poppins.variable} ${jetbrainsMono.variable}`}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
